[profile.default]
solc = '0.8.7'
src = 'contracts'
out = 'out'
libs = ["node_modules", "lib"]
test = 'test/foundry'
scripts = 'scripts'

remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@openzeppelin/contracts-upgradeable=node_modules/@openzeppelin/contracts-upgradeable',
    'forge-std=lib/forge-std/src/'
]

fuzz_runs = 5000
fuzz_max_global_rejects = 2_000_000
optimizer_runs = 200