[profile.default]
solc = '0.8.7'
src = 'contracts'
out = 'out'
libs = ["node_modules", "lib"]
test = 'test'
fs_permissions = [{ access = "read", path = "./" }]


script = 'scripts'
gas_reports = ["*"]

fuzz_runs = 5000
fuzz_max_global_rejects = 2_000_000
optimizer_runs = 200

[rpc_endpoints]
mainnet = "https://eth.llamarpc.com"