/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface VeBoostInterface extends utils.Interface {
  contractName: "VeBoost";
  functions: {
    "approve(address,uint256)": FunctionFragment;
    "safeTransferFrom(address,address,uint256)": FunctionFragment;
    "setApprovalForAll(address,bool)": FunctionFragment;
    "transferFrom(address,address,uint256)": FunctionFragment;
    "tokenURI(uint256)": FunctionFragment;
    "burn(uint256)": FunctionFragment;
    "create_boost(address,address,int256,uint256,uint256,uint256)": FunctionFragment;
    "extend_boost(uint256,int256,uint256,uint256)": FunctionFragment;
    "cancel_boost(uint256)": FunctionFragment;
    "batch_cancel_boosts(uint256[256])": FunctionFragment;
    "set_delegation_status(address,address,bool)": FunctionFragment;
    "batch_set_delegation_status(address,address[256],uint256[256])": FunctionFragment;
    "adjusted_balance_of(address)": FunctionFragment;
    "delegated_boost(address)": FunctionFragment;
    "received_boost(address)": FunctionFragment;
    "token_boost(uint256)": FunctionFragment;
    "token_expiry(uint256)": FunctionFragment;
    "token_cancel_time(uint256)": FunctionFragment;
    "calc_boost_bias_slope(address,int256,int256)": FunctionFragment;
    "get_token_id(address,uint256)": FunctionFragment;
    "commit_transfer_ownership(address)": FunctionFragment;
    "accept_transfer_ownership()": FunctionFragment;
    "set_base_uri(string)": FunctionFragment;
    "voting_escrow()": FunctionFragment;
    "balanceOf(address)": FunctionFragment;
    "getApproved(uint256)": FunctionFragment;
    "isApprovedForAll(address,address)": FunctionFragment;
    "ownerOf(uint256)": FunctionFragment;
    "name()": FunctionFragment;
    "symbol()": FunctionFragment;
    "base_uri()": FunctionFragment;
    "totalSupply()": FunctionFragment;
    "tokenByIndex(uint256)": FunctionFragment;
    "tokenOfOwnerByIndex(address,uint256)": FunctionFragment;
    "token_of_delegator_by_index(address,uint256)": FunctionFragment;
    "total_minted(address)": FunctionFragment;
    "account_expiries(address,uint256)": FunctionFragment;
    "admin()": FunctionFragment;
    "future_admin()": FunctionFragment;
    "grey_list(address,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "approve",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "burn", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "create_boost",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "extend_boost",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancel_boost",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "batch_cancel_boosts",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "set_delegation_status",
    values: [string, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "batch_set_delegation_status",
    values: [string, string[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "adjusted_balance_of",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "delegated_boost",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "received_boost",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "token_boost",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "token_expiry",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "token_cancel_time",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calc_boost_bias_slope",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "get_token_id",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "commit_transfer_ownership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "accept_transfer_ownership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "set_base_uri",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "voting_escrow",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "balanceOf", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(functionFragment: "base_uri", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenByIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenOfOwnerByIndex",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "token_of_delegator_by_index",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "total_minted",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "account_expiries",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "future_admin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grey_list",
    values: [string, string]
  ): string;

  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "create_boost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "extend_boost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancel_boost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batch_cancel_boosts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "set_delegation_status",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batch_set_delegation_status",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adjusted_balance_of",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "delegated_boost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "received_boost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "token_boost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "token_expiry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "token_cancel_time",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calc_boost_bias_slope",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "get_token_id",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commit_transfer_ownership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accept_transfer_ownership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "set_base_uri",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voting_escrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "base_uri", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenOfOwnerByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "token_of_delegator_by_index",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "total_minted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "account_expiries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "future_admin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grey_list", data: BytesLike): Result;

  events: {
    "Approval(address,address,uint256)": EventFragment;
    "ApprovalForAll(address,address,bool)": EventFragment;
    "Transfer(address,address,uint256)": EventFragment;
    "BurnBoost(address,address,uint256)": EventFragment;
    "DelegateBoost(address,address,uint256,uint256,uint256,uint256)": EventFragment;
    "ExtendBoost(address,address,uint256,uint256,uint256,uint256)": EventFragment;
    "TransferBoost(address,address,uint256,uint256,uint256)": EventFragment;
    "GreyListUpdated(address,address,bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Approval"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ApprovalForAll"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Transfer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BurnBoost"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DelegateBoost"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ExtendBoost"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TransferBoost"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GreyListUpdated"): EventFragment;
}

export type ApprovalEvent = TypedEvent<
  [string, string, BigNumber],
  { _owner: string; _approved: string; _token_id: BigNumber }
>;

export type ApprovalEventFilter = TypedEventFilter<ApprovalEvent>;

export type ApprovalForAllEvent = TypedEvent<
  [string, string, boolean],
  { _owner: string; _operator: string; _approved: boolean }
>;

export type ApprovalForAllEventFilter = TypedEventFilter<ApprovalForAllEvent>;

export type TransferEvent = TypedEvent<
  [string, string, BigNumber],
  { _from: string; _to: string; _token_id: BigNumber }
>;

export type TransferEventFilter = TypedEventFilter<TransferEvent>;

export type BurnBoostEvent = TypedEvent<
  [string, string, BigNumber],
  { _delegator: string; _receiver: string; _token_id: BigNumber }
>;

export type BurnBoostEventFilter = TypedEventFilter<BurnBoostEvent>;

export type DelegateBoostEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, BigNumber, BigNumber],
  {
    _delegator: string;
    _receiver: string;
    _token_id: BigNumber;
    _amount: BigNumber;
    _cancel_time: BigNumber;
    _expire_time: BigNumber;
  }
>;

export type DelegateBoostEventFilter = TypedEventFilter<DelegateBoostEvent>;

export type ExtendBoostEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, BigNumber, BigNumber],
  {
    _delegator: string;
    _receiver: string;
    _token_id: BigNumber;
    _amount: BigNumber;
    _expire_time: BigNumber;
    _cancel_time: BigNumber;
  }
>;

export type ExtendBoostEventFilter = TypedEventFilter<ExtendBoostEvent>;

export type TransferBoostEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, BigNumber],
  {
    _from: string;
    _to: string;
    _token_id: BigNumber;
    _amount: BigNumber;
    _expire_time: BigNumber;
  }
>;

export type TransferBoostEventFilter = TypedEventFilter<TransferBoostEvent>;

export type GreyListUpdatedEvent = TypedEvent<
  [string, string, boolean],
  { _receiver: string; _delegator: string; _status: boolean }
>;

export type GreyListUpdatedEventFilter = TypedEventFilter<GreyListUpdatedEvent>;

export interface VeBoost extends BaseContract {
  contractName: "VeBoost";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: VeBoostInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    approve(
      _approved: string,
      _token_id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "safeTransferFrom(address,address,uint256)"(
      _from: string,
      _to: string,
      _token_id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "safeTransferFrom(address,address,uint256,bytes)"(
      _from: string,
      _to: string,
      _token_id: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setApprovalForAll(
      _operator: string,
      _approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferFrom(
      _from: string,
      _to: string,
      _token_id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    tokenURI(
      _token_id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    burn(
      _token_id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    create_boost(
      _delegator: string,
      _receiver: string,
      _percentage: BigNumberish,
      _cancel_time: BigNumberish,
      _expire_time: BigNumberish,
      _id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    extend_boost(
      _token_id: BigNumberish,
      _percentage: BigNumberish,
      _expire_time: BigNumberish,
      _cancel_time: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    cancel_boost(
      _token_id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    batch_cancel_boosts(
      _token_ids: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    set_delegation_status(
      _receiver: string,
      _delegator: string,
      _status: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    batch_set_delegation_status(
      _receiver: string,
      _delegators: string[],
      _status: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    adjusted_balance_of(
      _account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    delegated_boost(
      _account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    received_boost(
      _account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    token_boost(
      _token_id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    token_expiry(
      _token_id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    token_cancel_time(
      _token_id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "calc_boost_bias_slope(address,int256,int256)"(
      _delegator: string,
      _percentage: BigNumberish,
      _expire_time: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    "calc_boost_bias_slope(address,int256,int256,uint256)"(
      _delegator: string,
      _percentage: BigNumberish,
      _expire_time: BigNumberish,
      _extend_token_id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    get_token_id(
      _delegator: string,
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    commit_transfer_ownership(
      _addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    accept_transfer_ownership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    set_base_uri(
      _base_uri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    voting_escrow(overrides?: CallOverrides): Promise<[string]>;

    balanceOf(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    getApproved(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    isApprovedForAll(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    ownerOf(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    name(overrides?: CallOverrides): Promise<[string]>;

    symbol(overrides?: CallOverrides): Promise<[string]>;

    base_uri(overrides?: CallOverrides): Promise<[string]>;

    totalSupply(overrides?: CallOverrides): Promise<[BigNumber]>;

    tokenByIndex(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    tokenOfOwnerByIndex(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    token_of_delegator_by_index(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    total_minted(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    account_expiries(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    admin(overrides?: CallOverrides): Promise<[string]>;

    future_admin(overrides?: CallOverrides): Promise<[string]>;

    grey_list(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  approve(
    _approved: string,
    _token_id: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "safeTransferFrom(address,address,uint256)"(
    _from: string,
    _to: string,
    _token_id: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "safeTransferFrom(address,address,uint256,bytes)"(
    _from: string,
    _to: string,
    _token_id: BigNumberish,
    _data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setApprovalForAll(
    _operator: string,
    _approved: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferFrom(
    _from: string,
    _to: string,
    _token_id: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  tokenURI(_token_id: BigNumberish, overrides?: CallOverrides): Promise<string>;

  burn(
    _token_id: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  create_boost(
    _delegator: string,
    _receiver: string,
    _percentage: BigNumberish,
    _cancel_time: BigNumberish,
    _expire_time: BigNumberish,
    _id: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  extend_boost(
    _token_id: BigNumberish,
    _percentage: BigNumberish,
    _expire_time: BigNumberish,
    _cancel_time: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  cancel_boost(
    _token_id: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  batch_cancel_boosts(
    _token_ids: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  set_delegation_status(
    _receiver: string,
    _delegator: string,
    _status: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  batch_set_delegation_status(
    _receiver: string,
    _delegators: string[],
    _status: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  adjusted_balance_of(
    _account: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  delegated_boost(
    _account: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  received_boost(
    _account: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  token_boost(
    _token_id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  token_expiry(
    _token_id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  token_cancel_time(
    _token_id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "calc_boost_bias_slope(address,int256,int256)"(
    _delegator: string,
    _percentage: BigNumberish,
    _expire_time: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  "calc_boost_bias_slope(address,int256,int256,uint256)"(
    _delegator: string,
    _percentage: BigNumberish,
    _expire_time: BigNumberish,
    _extend_token_id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  get_token_id(
    _delegator: string,
    _id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  commit_transfer_ownership(
    _addr: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  accept_transfer_ownership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  set_base_uri(
    _base_uri: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  voting_escrow(overrides?: CallOverrides): Promise<string>;

  balanceOf(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  getApproved(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  isApprovedForAll(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  ownerOf(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  name(overrides?: CallOverrides): Promise<string>;

  symbol(overrides?: CallOverrides): Promise<string>;

  base_uri(overrides?: CallOverrides): Promise<string>;

  totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

  tokenByIndex(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  tokenOfOwnerByIndex(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  token_of_delegator_by_index(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  total_minted(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  account_expiries(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  admin(overrides?: CallOverrides): Promise<string>;

  future_admin(overrides?: CallOverrides): Promise<string>;

  grey_list(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    approve(
      _approved: string,
      _token_id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "safeTransferFrom(address,address,uint256)"(
      _from: string,
      _to: string,
      _token_id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "safeTransferFrom(address,address,uint256,bytes)"(
      _from: string,
      _to: string,
      _token_id: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    setApprovalForAll(
      _operator: string,
      _approved: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    transferFrom(
      _from: string,
      _to: string,
      _token_id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    tokenURI(
      _token_id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    burn(_token_id: BigNumberish, overrides?: CallOverrides): Promise<void>;

    create_boost(
      _delegator: string,
      _receiver: string,
      _percentage: BigNumberish,
      _cancel_time: BigNumberish,
      _expire_time: BigNumberish,
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    extend_boost(
      _token_id: BigNumberish,
      _percentage: BigNumberish,
      _expire_time: BigNumberish,
      _cancel_time: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    cancel_boost(
      _token_id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    batch_cancel_boosts(
      _token_ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    set_delegation_status(
      _receiver: string,
      _delegator: string,
      _status: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    batch_set_delegation_status(
      _receiver: string,
      _delegators: string[],
      _status: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    adjusted_balance_of(
      _account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    delegated_boost(
      _account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    received_boost(
      _account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    token_boost(
      _token_id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    token_expiry(
      _token_id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    token_cancel_time(
      _token_id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "calc_boost_bias_slope(address,int256,int256)"(
      _delegator: string,
      _percentage: BigNumberish,
      _expire_time: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    "calc_boost_bias_slope(address,int256,int256,uint256)"(
      _delegator: string,
      _percentage: BigNumberish,
      _expire_time: BigNumberish,
      _extend_token_id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    get_token_id(
      _delegator: string,
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    commit_transfer_ownership(
      _addr: string,
      overrides?: CallOverrides
    ): Promise<void>;

    accept_transfer_ownership(overrides?: CallOverrides): Promise<void>;

    set_base_uri(_base_uri: string, overrides?: CallOverrides): Promise<void>;

    voting_escrow(overrides?: CallOverrides): Promise<string>;

    balanceOf(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    getApproved(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    isApprovedForAll(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    ownerOf(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    name(overrides?: CallOverrides): Promise<string>;

    symbol(overrides?: CallOverrides): Promise<string>;

    base_uri(overrides?: CallOverrides): Promise<string>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    tokenByIndex(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenOfOwnerByIndex(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    token_of_delegator_by_index(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    total_minted(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    account_expiries(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    admin(overrides?: CallOverrides): Promise<string>;

    future_admin(overrides?: CallOverrides): Promise<string>;

    grey_list(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "Approval(address,address,uint256)"(
      _owner?: string | null,
      _approved?: string | null,
      _token_id?: BigNumberish | null
    ): ApprovalEventFilter;
    Approval(
      _owner?: string | null,
      _approved?: string | null,
      _token_id?: BigNumberish | null
    ): ApprovalEventFilter;

    "ApprovalForAll(address,address,bool)"(
      _owner?: string | null,
      _operator?: string | null,
      _approved?: null
    ): ApprovalForAllEventFilter;
    ApprovalForAll(
      _owner?: string | null,
      _operator?: string | null,
      _approved?: null
    ): ApprovalForAllEventFilter;

    "Transfer(address,address,uint256)"(
      _from?: string | null,
      _to?: string | null,
      _token_id?: BigNumberish | null
    ): TransferEventFilter;
    Transfer(
      _from?: string | null,
      _to?: string | null,
      _token_id?: BigNumberish | null
    ): TransferEventFilter;

    "BurnBoost(address,address,uint256)"(
      _delegator?: string | null,
      _receiver?: string | null,
      _token_id?: BigNumberish | null
    ): BurnBoostEventFilter;
    BurnBoost(
      _delegator?: string | null,
      _receiver?: string | null,
      _token_id?: BigNumberish | null
    ): BurnBoostEventFilter;

    "DelegateBoost(address,address,uint256,uint256,uint256,uint256)"(
      _delegator?: string | null,
      _receiver?: string | null,
      _token_id?: BigNumberish | null,
      _amount?: null,
      _cancel_time?: null,
      _expire_time?: null
    ): DelegateBoostEventFilter;
    DelegateBoost(
      _delegator?: string | null,
      _receiver?: string | null,
      _token_id?: BigNumberish | null,
      _amount?: null,
      _cancel_time?: null,
      _expire_time?: null
    ): DelegateBoostEventFilter;

    "ExtendBoost(address,address,uint256,uint256,uint256,uint256)"(
      _delegator?: string | null,
      _receiver?: string | null,
      _token_id?: BigNumberish | null,
      _amount?: null,
      _expire_time?: null,
      _cancel_time?: null
    ): ExtendBoostEventFilter;
    ExtendBoost(
      _delegator?: string | null,
      _receiver?: string | null,
      _token_id?: BigNumberish | null,
      _amount?: null,
      _expire_time?: null,
      _cancel_time?: null
    ): ExtendBoostEventFilter;

    "TransferBoost(address,address,uint256,uint256,uint256)"(
      _from?: string | null,
      _to?: string | null,
      _token_id?: BigNumberish | null,
      _amount?: null,
      _expire_time?: null
    ): TransferBoostEventFilter;
    TransferBoost(
      _from?: string | null,
      _to?: string | null,
      _token_id?: BigNumberish | null,
      _amount?: null,
      _expire_time?: null
    ): TransferBoostEventFilter;

    "GreyListUpdated(address,address,bool)"(
      _receiver?: string | null,
      _delegator?: string | null,
      _status?: null
    ): GreyListUpdatedEventFilter;
    GreyListUpdated(
      _receiver?: string | null,
      _delegator?: string | null,
      _status?: null
    ): GreyListUpdatedEventFilter;
  };

  estimateGas: {
    approve(
      _approved: string,
      _token_id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "safeTransferFrom(address,address,uint256)"(
      _from: string,
      _to: string,
      _token_id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "safeTransferFrom(address,address,uint256,bytes)"(
      _from: string,
      _to: string,
      _token_id: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setApprovalForAll(
      _operator: string,
      _approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferFrom(
      _from: string,
      _to: string,
      _token_id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    tokenURI(
      _token_id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    burn(
      _token_id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    create_boost(
      _delegator: string,
      _receiver: string,
      _percentage: BigNumberish,
      _cancel_time: BigNumberish,
      _expire_time: BigNumberish,
      _id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    extend_boost(
      _token_id: BigNumberish,
      _percentage: BigNumberish,
      _expire_time: BigNumberish,
      _cancel_time: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    cancel_boost(
      _token_id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    batch_cancel_boosts(
      _token_ids: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    set_delegation_status(
      _receiver: string,
      _delegator: string,
      _status: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    batch_set_delegation_status(
      _receiver: string,
      _delegators: string[],
      _status: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    adjusted_balance_of(
      _account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    delegated_boost(
      _account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    received_boost(
      _account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    token_boost(
      _token_id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    token_expiry(
      _token_id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    token_cancel_time(
      _token_id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "calc_boost_bias_slope(address,int256,int256)"(
      _delegator: string,
      _percentage: BigNumberish,
      _expire_time: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "calc_boost_bias_slope(address,int256,int256,uint256)"(
      _delegator: string,
      _percentage: BigNumberish,
      _expire_time: BigNumberish,
      _extend_token_id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    get_token_id(
      _delegator: string,
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    commit_transfer_ownership(
      _addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    accept_transfer_ownership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    set_base_uri(
      _base_uri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    voting_escrow(overrides?: CallOverrides): Promise<BigNumber>;

    balanceOf(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    getApproved(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isApprovedForAll(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ownerOf(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    symbol(overrides?: CallOverrides): Promise<BigNumber>;

    base_uri(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    tokenByIndex(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenOfOwnerByIndex(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    token_of_delegator_by_index(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    total_minted(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    account_expiries(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    admin(overrides?: CallOverrides): Promise<BigNumber>;

    future_admin(overrides?: CallOverrides): Promise<BigNumber>;

    grey_list(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    approve(
      _approved: string,
      _token_id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "safeTransferFrom(address,address,uint256)"(
      _from: string,
      _to: string,
      _token_id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "safeTransferFrom(address,address,uint256,bytes)"(
      _from: string,
      _to: string,
      _token_id: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setApprovalForAll(
      _operator: string,
      _approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferFrom(
      _from: string,
      _to: string,
      _token_id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    tokenURI(
      _token_id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    burn(
      _token_id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    create_boost(
      _delegator: string,
      _receiver: string,
      _percentage: BigNumberish,
      _cancel_time: BigNumberish,
      _expire_time: BigNumberish,
      _id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    extend_boost(
      _token_id: BigNumberish,
      _percentage: BigNumberish,
      _expire_time: BigNumberish,
      _cancel_time: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    cancel_boost(
      _token_id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    batch_cancel_boosts(
      _token_ids: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    set_delegation_status(
      _receiver: string,
      _delegator: string,
      _status: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    batch_set_delegation_status(
      _receiver: string,
      _delegators: string[],
      _status: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    adjusted_balance_of(
      _account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    delegated_boost(
      _account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    received_boost(
      _account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    token_boost(
      _token_id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    token_expiry(
      _token_id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    token_cancel_time(
      _token_id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "calc_boost_bias_slope(address,int256,int256)"(
      _delegator: string,
      _percentage: BigNumberish,
      _expire_time: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "calc_boost_bias_slope(address,int256,int256,uint256)"(
      _delegator: string,
      _percentage: BigNumberish,
      _expire_time: BigNumberish,
      _extend_token_id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    get_token_id(
      _delegator: string,
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    commit_transfer_ownership(
      _addr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    accept_transfer_ownership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    set_base_uri(
      _base_uri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    voting_escrow(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    balanceOf(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getApproved(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isApprovedForAll(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ownerOf(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    symbol(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    base_uri(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalSupply(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokenByIndex(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokenOfOwnerByIndex(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    token_of_delegator_by_index(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    total_minted(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    account_expiries(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    admin(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    future_admin(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    grey_list(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
